// Writes supabase/seed.sql from data/games.json using the engine.
// Answer lists and totals come from the engine, never hand typing. Idempotent (upserts).
// Holidays (data/holidays.json) go through the same rule as the client, so the server's daily always matches.
// Run: npm run db:seed:gen

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildHiddenWords } from '../src/engine/hiddenWords';
import { dailyIdFor, games } from '../src/games/catalog';

/** Days to schedule ahead. 2026-01-01 is day 1. */
const DAYS = 1100;

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const qJson = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const out: string[] = [
  '-- Generated by scripts/gen-seed.ts from data/games.json. Do not edit by hand.',
  '',
  'insert into public.games (id, kind, type, category, title, noun, text, dict) values',
  games
    .map(
      (g) =>
        `  (${q(g.id)}, 'curated', ${q(g.type)}, ${q(g.category)}, ${q(g.title)}, ${q(g.noun)}, ${q(g.text)}, ${qJson(g.dict)})`,
    )
    .join(',\n'),
  'on conflict (id) do update set category = excluded.category, title = excluded.title, noun = excluded.noun,',
  '  text = excluded.text, dict = excluded.dict;',
  '',
];

const answers = new Map(games.map((g) => [g.id, buildHiddenWords(g).answers.map((a) => a.key)]));

const days = Array.from({ length: DAYS }, (_, i) => i + 1);
out.push(
  'insert into public.daily (day_no, game_id) values',
  days.map((n) => `  (${n}, ${q(dailyIdFor(n))})`).join(',\n'),
  'on conflict (day_no) do update set game_id = excluded.game_id;',
  '',
  'insert into public.daily_answers (day_no, answers) values',
  days
    .map((n) => {
      const keys = answers.get(dailyIdFor(n))!;
      return `  (${n}, array[${keys.map(q).join(', ')}]::text[])`;
    })
    .join(',\n'),
  'on conflict (day_no) do update set answers = excluded.answers;',
  '',
);

const file = join(import.meta.dirname, '..', 'supabase', 'seed.sql');
writeFileSync(file, out.join('\n'));
console.log(`Wrote ${file}: ${games.length} games, ${DAYS} days.`);
